### ISSUE TITLE
steem.broadcast.vote does not call callback function

### ISSUE THREAD

**Issue by evm2p** [adcpm/steem#51]
```
var steem = require('steem');

var wif = steem.auth.toWif(username, password, 'posting');
steem.broadcast.vote(wif, voter, author, permlink, weight, function(err, result) {
    console.log(err, result);
});
```

I think this is wrong because the file [lib/broadcast/operations.json](/lib/broadcast/operations.json) shows no ```wif``` parameter.

```
{
    "roles": [
      "posting"
    ],
    "operation": "vote",
    "params": [
      "voter",
      "author",
      "permlink",
      "weight"
    ]
  },
```

Do we require a login operation before vote can be used? If so, why did you remove the WIF? That is more useful.

**Comment by yamadapc** [comment]
It doesn't require a login and the `wif` is always the first parameter for all broadcast methods, followed by `params` in that JSON file.

I added a test-case for this issue on https://github.com/adcpm/steem/commit/c686a5ce4fd2f1d1088dc1c6a871e7eb11de55a9. Your code should work fine as well. I also ran it isolated to make sure there was no setup requirement bug.

If you could, try modifying the test code above and seeing if you have the issue installing with:

```
npm install --save adcpm/steem#df2147146d80cf09b2afeb64265d861019f2695d
```

You might have the non-development build of steem. If you could provide the version you have installed I can troubleshoot it as well, since the `dev` branch should be still getting battle-tested.

**Comment by evm2p** [comment]
I'm sorry, I confused myself, I had a null parameter when I was using it.

Thanks for your quick response!

**Comment by yamadapc** [comment]
No worries, closing it as a non-bug then. Good week & thanks!
